package ar.edu.unlu.casitarobada.juego;

public enum EventosCasitaRobada {
	JUEGO_INICIADO, FIN_DEL_JUEGO, TURNO_CAMBIADO, JUGADOR_AGREGADO, CARTA_TIRADA, CARTA_ROBADA, CASA_ROBADA, CARTAS_SOPLADAS, CARGAR_JUEGO, VER_TOP, CARTAS_NO_SOPLADAS
}